export const DEKANATY: Record<string, string[]> = {
  'Archidiecezja białostocka': [
    'Białystok Bacieczki', 'Białystok Białostoczek', 'Białystok Dojlidy', 'Białystok Nowe Miasto',
    'Białystok Starosielce', 'Białystok Śródmieście', 'Dąbrowa Białostocka', 'Knyszyn',
    'Korycin', 'Krynki', 'Mońki', 'Sokółka', 'Wasilków',
  ],
  'Archidiecezja częstochowska': [
    'Blachownia', 'Brzeźnica nad Wartą', 'Częstochowa – NMP Jasnogórskiej', 'Częstochowa – Podwyższenia Krzyża Świętego',
    'Częstochowa – św. Antoniego z Padwy', 'Częstochowa – św. Józefa', 'Częstochowa – św. Wojciecha',
    'Częstochowa – św. Zygmunta', 'Działoszyn', 'Gidle', 'Gorzkowice', 'Kłobuck', 'Kłomnice',
    'Kodrąb', 'Koziegłowy', 'Krzepice', 'Miedźno', 'Mokrsko', 'Mstów', 'Mykanów', 'Myszków',
    'NMP Królowej Polski w Zawierciu', 'Olsztyn', 'Osjaków', 'Pajęczno', 'Poraj', 'Praszka',
    'Radomsko – NSJ', 'Radomsko – św. Lamberta', 'Rozprza', 'Sulmierzyce',
    'Świętych Ap. Piotra i Pawła w Zawierciu', 'Truskolasy', 'Wieluń – NMP Pocieszenia',
    'Wieluń – św. Wojciecha', 'Żarki',
  ],
  'Archidiecezja gdańska': [
    'Gdańsk Dolne Miasto', 'Gdańsk Łostowice', 'Gdańsk Oliwa', 'Gdańsk Przymorze',
    'Gdańsk Siedlce', 'Gdańsk Śródmieście', 'Gdańsk Wrzeszcz', 'Gdynia Chylonia',
    'Gdynia Oksywie', 'Gdynia Orłowo', 'Gdynia Śródmieście', 'Kielno', 'Kolbudy',
    'Luzino', 'Morski', 'Pruszcz Gdański', 'Puck', 'Reda', 'Sopot', 'Trąbki Wielkie',
    'Wejherowo', 'Żarnowiec', 'Żukowo', 'Żuławy Steblewskie',
  ],
  'Archidiecezja gnieźnieńska': [
    'Barciński', 'Chodzieski', 'Damasławski', 'Gnieźnieński I', 'Gnieźnieński II',
    'Gniewkowski', 'Goliński', 'Gośliński', 'Inowrocławski I', 'Inowrocławski II',
    'Kiszkowski', 'Kleczewski', 'Kłecki', 'Kruszwicki', 'Miłosławski', 'Mogileński',
    'Pobiedziski', 'Rogoziński', 'Rogowski', 'Słupecki', 'Strzaleński', 'Strzałkowski',
    'Trzemeszeński', 'Wągrowiecki', 'Witkowski', 'Wrzesiński I', 'Wrzesiński II',
    'Zagórowski', 'Złotnicki', 'Żniński',
  ],
  'Archidiecezja katowicka': [
    'Bieruń', 'Chorzów', 'Chorzów-Batory', 'Dębieńsko', 'Golejów', 'Gorzyce',
    'Jastrzębie Górne', 'Jastrzębie-Zdrój', 'Katowice-Bogucice', 'Katowice-Panewniki',
    'Katowice-Piotrowice', 'Katowice-Śródmieście', 'Katowice-Załęże', 'Knurów',
    'Kochłowice', 'Lędziny', 'Łaziska', 'Miedźna', 'Mikołów', 'Mysłowice', 'Niedobczyce',
    'Orzesze', 'Pawłowice Śląskie', 'Piekary Śląskie', 'Pogrzebień', 'Pszczyna', 'Pszów',
    'Ruda Śląska', 'Rybnik', 'Rybnik-Boguszowice', 'Siemianowice Śląskie', 'Suszec',
    'Świętochłowice', 'Tychy Nowe', 'Tychy Stare', 'Wodzisław Śląski', 'Żory',
  ],
  'Archidiecezja krakowska': [
    'Babice', 'Białka Tatrzańska', 'Biały Dunajec', 'Bolechowice', 'Chrzanów',
    'Czarny Dunajec', 'Czernichów', 'Dobczyce', 'Jabłonka', 'Jordanów', 'Kalwaria',
    'Kraków 1 – Centrum', 'Kraków 2 – Kazimierz', 'Kraków 3 – Salwator',
    'Kraków 4 – Bronowice', 'Kraków 5 – Krowodrza', 'Kraków 6 – Prądnik',
    'Kraków 7 – Podgórze', 'Kraków 8 – Prokocim', 'Kraków 9 – Borek Fałęcki',
    'Kraków 10 – Mogiła', 'Kraków 11 – Bieńczyce', 'Krzeszowice', 'Libiąż',
    'Maków Podhalański', 'Mogilany', 'Mszana Dolna', 'Myślenice', 'Niedzica', 'Niegowić',
    'Niepołomice', 'Nowy Targ', 'Pcim', 'Rabka', 'Skawina', 'Sucha Beskidzka',
    'Sułkowice', 'Trzebinia', 'Wadowice Północ', 'Wadowice Południe', 'Wawrzeńczyce',
    'Wieliczka Wschód', 'Wieliczka Zachód', 'Zakopane', 'Zator',
  ],
  'Archidiecezja lubelska': [
    'Bełżycki', 'Bychawski', 'Chełmski – wschodni', 'Chełmski – zachodni', 'Czemiernicki',
    'Garbowski', 'Kazimierski', 'Konopnicki', 'Krasnostawski – wschodni',
    'Krasnostawski – zachodni', 'Kraśnicki', 'Lubartowski', 'Lubelski – podmiejski',
    'Lubelski – południowy', 'Lubelski – północny', 'Lubelski – śródmiejski',
    'Lubelski – wschodni', 'Lubelski – zachodni', 'Łęczyński', 'Michowski', 'Opolski',
    'Piasecki', 'Puławski', 'Siedliski', 'Świdnicki', 'Turobiński', 'Urzędowski', 'Zakrzowiecki',
  ],
  'Archidiecezja łódzka': [
    'Aleksandrowski', 'Bełchatowski', 'Brzeziński', 'Dłutowski', 'Karsznice', 'Koluszkowski',
    'Konstantynowski', 'Krzepczowski', 'Kurowicki', 'Łaski', 'Łódź-Bałuty',
    'Łódź-Chojny-Dąbrowa', 'Łódź-Olechów', 'Łódź-Radogoszcz', 'Łódź-Retkinia-Ruda',
    'Łódź-Stoki', 'Łódź-Śródmieście', 'Łódź-Teofilów-Żubardź', 'Łódź-Widzew',
    'Ozorkowski', 'Pabianicki', 'Piotrkowski', 'Poddębicki', 'Strykowski', 'Sulejowski',
    'Zelowski', 'Zgierski',
  ],
  'Archidiecezja poznańska': [
    'Borecki', 'Bukowski', 'Czarnkowski', 'Czerwonacki', 'Gostyński', 'Grodziski',
    'Jutrosiński', 'Komornicki', 'Kostrzyński', 'Kościański', 'Kórnicki', 'Krobski',
    'Krzywiński', 'Leszczyński', 'Luboński', 'Lwówecki', 'Międzychodzki', 'Nowomiejski',
    'Obornicki', 'Pniewski', 'Poznań – Jeżyce', 'Poznań – Łazarz', 'Poznań – Nowe Miasto',
    'Poznań – Piątkowo', 'Poznań – Rataje', 'Poznań – Stare Miasto', 'Poznań – Starołęka',
    'Poznań – Winogrady', 'Przeźmierowski', 'Przemęcki', 'Puszczykowski', 'Rawicki',
    'Rydzyński', 'Stęszewski', 'Swarzędzki', 'Szamotulski', 'Śmigielski', 'Średzki',
    'Śremski', 'Święciechowski', 'Wieleński', 'Wolsztyński', 'Wroniecki', 'Zbąszyński',
  ],
  'Archidiecezja przemyska': [
    'Bircza', 'Błażowa', 'Brzozów', 'Domaradz', 'Dubiecko', 'Dukla', 'Dynów', 'Grabownica',
    'Jaćmierz', 'Kalwaria Pacławska', 'Kańczuga', 'Krosno I', 'Krosno II', 'Krosno III',
    'Leżajsk I', 'Leżajsk II', 'Łańcut I', 'Łańcut II', 'Miejsce Piastowe',
    'Przeworsk I', 'Przeworsk II', 'Przemyśl I', 'Przemyśl II', 'Przemyśl III',
    'Pruchnik', 'Rymanów', 'Rzepedź', 'Sanok I', 'Sanok II', 'Sieniawa', 'Żołynia', 'Żurawica',
  ],
  'Archidiecezja szczecińsko-kamieńska': [
    'Banie', 'Barlinek', 'Cedynia', 'Chojna', 'Choszczno', 'Dębno', 'Drawno', 'Golczewo',
    'Goleniów', 'Gryfice', 'Gryfino', 'Ińsko', 'Kamień Pomorski', 'Kołbacz', 'Lipiany',
    'Łobez', 'Maszewo', 'Mieszkowice', 'Myślibórz', 'Nowogard', 'Police', 'Pyrzyce',
    'Resko', 'Stargard Wschód', 'Stargard Zachód', 'Suchań', 'Szczecin-Dąbie',
    'Szczecin-Niebuszewo', 'Szczecin-Pogodno', 'Szczecin-Pomorzany', 'Szczecin-Słoneczne',
    'Szczecin-Śródmieście', 'Szczecin-Żelechowa', 'Świnoujście', 'Trzebiatów', 'Wolin',
  ],
  'Archidiecezja warmińska': [
    'Barczewo', 'Bartoszyce', 'Biskupiec Reszelski', 'Braniewo', 'Dobre Miasto', 'Frombork',
    'Górowo Iławeckie', 'Grunwald', 'Jeziorany', 'Kętrzyn I – Południowy Zachód',
    'Kętrzyn II – Północny Wschód', 'Kozłowo', 'Lidzbark Warmiński', 'Łukta',
    'Mrągowo I', 'Mrągowo II', 'Nidzica', 'Olsztyn I – Śródmieście', 'Olsztyn II – Zatorze',
    'Olsztyn III – Gutkowo', 'Olsztyn IV – Jaroty', 'Olsztyn V – Kormoran', 'Olsztynek',
    'Orneta', 'Ostróda – Wschód', 'Ostróda – Zachód', 'Pasym', 'Pieniężno', 'Reszel',
    'Rozogi', 'Sępopol', 'Szczytno', 'Świątki',
  ],
  'Archidiecezja warszawska': [
    'Bielański', 'Błoński', 'Brwinowski', 'Czerski', 'Grodziski', 'Grójecki', 'Jelonkowski',
    'Kampinoski', 'Konstanciński', 'Lasecki', 'Mogielnicki', 'Mokotowski', 'Ochocki',
    'Piaseczyński', 'Pruszkowski', 'Raszyński', 'Służewski', 'Staromiejski', 'Śródmiejski',
    'Świętokrzyski', 'Tarczyński', 'Ursuski', 'Ursynowski', 'Warecki', 'Wilanowski',
    'Wolski', 'Żoliborski',
  ],
  'Archidiecezja wrocławska': [
    'Borów', 'Brzeg – południe', 'Brzeg – północ', 'Brzeg Dolny', 'Góra – wschód',
    'Góra – zachód', 'Jelcz-Laskowice', 'Kąty Wrocławskie', 'Miękinia', 'Milicz',
    'Namysłów – wschód', 'Namysłów – zachód', 'Oleśnica – wschód', 'Oleśnica – zachód',
    'Oława', 'Prusice', 'Sobótka', 'Strzelin', 'Środa Śląska', 'Trzebnica', 'Wiązów',
    'Wołów', 'Wrocław – Katedra', 'Wrocław – Krzyki', 'Wrocław – południe',
    'Wrocław – północ I (Osobowice)', 'Wrocław – północ II (Sępolno)',
    'Wrocław – północ III (Psie Pole)', 'Wrocław – Śródmieście', 'Wrocław – wschód',
    'Wrocław – zachód (Kozanów)', 'Wrocław – zachód (Leśnica)', 'Ziębice',
  ],
  'Diecezja bielsko-żywiecka': [
    'Andrychów', 'Bielsko-Biała I – Centrum', 'Bielsko-Biała II – Stare Bielsko',
    'Bielsko-Biała III – Wschód', 'Cieszyn', 'Czechowicki', 'Goleszów', 'Istebna',
    'Jasienica', 'Jawiszowice', 'Jeleśnia', 'Kęty', 'Łodygowice', 'Międzybrodzie',
    'Milówka', 'Osiek', 'Oświęcim', 'Radziechowy', 'Skoczów', 'Strumień', 'Wilamowice',
    'Wisła', 'Żywiec',
  ],
  'Diecezja bydgoska': [
    'Białe Błota', 'Bydgoszcz I', 'Bydgoszcz II', 'Bydgoszcz III', 'Bydgoszcz IV',
    'Bydgoszcz V', 'Bydgoszcz VI', 'Kcynia', 'Łabiszyn', 'Łobżenica', 'Mrocza', 'Nakło',
    'Osielsko', 'Osowa Góra', 'Sępólno Krajeńskie', 'Solec Kujawski', 'Szubin', 'Wyrzysk',
    'Wysoka', 'Złotów I', 'Złotów II',
  ],
  'Diecezja drohiczyńska': [
    'Bielsk Podlaski', 'Brańsk', 'Ciechanowiec', 'Drohiczyn', 'Hajnówka', 'Łochów',
    'Sarnaki', 'Siemiatycze', 'Sokołów Podlaski', 'Sterdyń', 'Węgrów',
  ],
  'Diecezja elbląska': [
    'Dzierzgoń', 'Elbląg Południe', 'Elbląg Północ', 'Elbląg Śródmieście',
    'Iława – Wschód', 'Iława – Zachód', 'Krynica Morska', 'Kwidzyn – Śródmieście',
    'Kwidzyn – Zatorze', 'Malbork I', 'Malbork II', 'Miłomłyn', 'Morąg', 'Nowy Dwór Gdański',
    'Nowy Staw', 'Pasłęk I', 'Pasłęk II', 'Prabuty', 'Susz', 'Sztum', 'Tolkmicko',
  ],
  'Diecezja ełcka': [
    'Augustów – Matki Bożej Królowej Polski', 'Augustów – św. Bartłomieja Apostoła',
    'Biała Piska', 'Ełk – Matki Bożej Fatimskiej', 'Ełk – Miłosierdzia Bożego',
    'Ełk – Świętej Rodziny', 'Filipów', 'Giżycko – św. Krzysztofa',
    'Giżycko – św. Szczepana Męczennika', 'Gołdap', 'Lipsk', 'Mikołajki',
    'Olecko – NMP', 'Olecko – św. Jana Apostoła', 'Orzysz', 'Pisz', 'Rajgród',
    'Sejny', 'Suwałki – Ducha Świętego', 'Suwałki – Miłosierdzia Bożego',
    'Suwałki – św. Benedykta i Romualda', 'Węgorzewo',
  ],
  'Diecezja gliwicka': [
    'Bytom', 'Bytom-Miechowice', 'Gliwice', 'Gliwice-Łabędy', 'Gliwice-Sośnica',
    'Kuźnia Raciborska', 'Lubliniec', 'Pławniowice', 'Pyskowice', 'Sadów',
    'Tarnowskie Góry', 'Toszek', 'Woźniki', 'Zabrze', 'Zabrze-Mikulczyce', 'Żyglin',
  ],
  'Diecezja kaliska': [
    'Błaszki', 'Bolesławiec', 'Bralin', 'Czermin', 'Dobrzyca', 'Gołuchów', 'Grabów',
    'Jarocin', 'Kalisz I', 'Kalisz II', 'Kępno', 'Koźmin', 'Koźminek', 'Krotoszyn',
    'Lututów', 'Mikstat', 'Odolanów', 'Ołobok', 'Opatówek', 'Ostrów Wielkopolski I',
    'Ostrów Wielkopolski II', 'Ostrzeszów', 'Pleszew', 'Raszków', 'Stawiszyn', 'Syców',
    'Trzcinica', 'Twardogóra', 'Wieruszów', 'Wołczyn', 'Zduny', 'Złoczew', 'Żerków',
  ],
  'Diecezja kielecka': [
    'Bodzentyński', 'Buski', 'Chęciński', 'Chmielnicki', 'Daleszycki', 'Jędrzejowski',
    'Kazimierski', 'Kielce-Południe', 'Kielce-Północ', 'Kielce-Śródmieście',
    'Kielce-Zachód', 'Koniecpolski', 'Lelowski', 'Łopuszański', 'Małogoski', 'Masłowski',
    'Miechowski', 'Morawicki', 'Nowokorczyński', 'Piekoszowski', 'Pińczowski',
    'Proszowicki', 'Sędziszowski', 'Skalski', 'Skalbmierski', 'Słomnicki', 'Stopnicki',
    'Szczekociński', 'Wiślicki', 'Włoszczowski', 'Wodzisławski', 'Zagnański', 'Żarnowiecki',
  ],
  'Diecezja koszalińsko-kołobrzeska': [
    'Barwice', 'Białogard', 'Bobolice', 'Czarne', 'Darłowo', 'Drawsko Pomorskie',
    'Gościno', 'Jastrowie', 'Kołobrzeg', 'Koszalin', 'Miastko', 'Mielno', 'Mirosławiec',
    'Piła', 'Polanów', 'Połczyn-Zdrój', 'Sławno', 'Słupsk Wschód', 'Słupsk Zachód',
    'Szczecinek', 'Świdwin', 'Trzcianka', 'Ustka', 'Wałcz',
  ],
  'Diecezja legnicka': [
    'Bogatynia', 'Bolesławiec Wschód', 'Bolesławiec Zachód', 'Chocianów', 'Chojnów',
    'Gryfów Śląski', 'Jawor', 'Jelenia Góra Wschód', 'Jelenia Góra Zachód',
    'Kamienna Góra Wschód', 'Kamienna Góra Zachód', 'Karpacz', 'Legnica Katedra',
    'Legnica Wschód', 'Legnica Zachód', 'Leśna', 'Lubań', 'Lubin Wschód', 'Lubin Zachód',
    'Lwówek Śląski', 'Nowogrodziec', 'Polkowice', 'Prochowice', 'Szklarska Poręba',
    'Ścinawa', 'Świerzawa', 'Węgliniec', 'Złotoryja', 'Zgorzelec',
  ],
  'Diecezja łomżyńska': [
    'Chorzele', 'Czyżew', 'Grajewo', 'Jedwabne', 'Kadzidło', 'Kobylin', 'Kolno',
    'Krasnosielc', 'Łapy', 'Łomża – św. Brunona', 'Łomża – św. Michała Archanioła',
    'Myszyniec', 'Ostrołęka – Nawiedzenia NMP', 'Ostrołęka – św. Antoniego',
    'Ostrów Mazowiecka – Chrystusa Dobrego Pasterza', 'Ostrów Mazowiecka – Wniebowzięcia NMP',
    'Piątnica', 'Różan', 'Rzekuń', 'Szczuczyn', 'Szepietowo', 'Wysokie Mazowieckie',
    'Wyszków', 'Zambrów',
  ],
  'Diecezja łowicka': [
    'Biała Rawska', 'Głowno', 'Krośniewice', 'Kutno – św. Michała Archanioła',
    'Kutno – św. Wawrzyńca', 'Lubochnia', 'Łęczyca', 'Łowicz – Św. Ducha',
    'Łowicz-Katedra', 'Mszczonów', 'Nowe Miasto nad Pilicą', 'Piątek', 'Rawa Mazowiecka',
    'Sanniki', 'Skierniewice – NSJ', 'Skierniewice – św. Jakuba',
    'Sochaczew – Matki Bożej Nieustającej Pomocy', 'Sochaczew – św. Wawrzyńca',
    'Wiskitki', 'Żychlin', 'Żyrardów',
  ],
  'Diecezja opolska': [
    'Biała', 'Branice', 'Dobrodzień', 'Głogówek', 'Głubczyce', 'Głuchołazy', 'Gorzów Śląski',
    'Gościęcin', 'Grodków', 'Kamień Śląski', 'Kędzierzyn', 'Kietrz', 'Kluczbork', 'Koźle',
    'Krapkowice', 'Leśnica', 'Łany', 'Niemodlin', 'Nysa', 'Olesno', 'Opole',
    'Opole-Szczepanowice', 'Otmuchów', 'Ozimek', 'Paczków', 'Pietrowice Wielkie',
    'Prószków', 'Prudnik', 'Racibórz', 'Siołkowice', 'Skoroszyce', 'Strzelce Opolskie',
    'Tworków', 'Ujazd Śląski', 'Zagwiździe', 'Zawadzkie',
  ],
  'Diecezja pelplińska': [
    'Borzyszkowski', 'Bruski', 'Bytowski', 'Chojnicki', 'Człuchowski', 'Czerski',
    'Gniewski', 'Gniewiński', 'Główczycki', 'Jeżewski', 'Kamieński', 'Kartuski',
    'Koronowski', 'Kościerski', 'Lęborski', 'Lubiewski', 'Łebski', 'Łupawski', 'Nowski',
    'Pelpliński', 'Rytelski', 'Sierakowicki', 'Skarszewski', 'Skórzecki', 'Starogardzki',
    'Stężycki', 'Świecki', 'Tczewski', 'Tucholski', 'Zblewski',
  ],
  'Diecezja płocka': [
    'Bielski', 'Bodzanowski', 'Ciechanowski wschodni', 'Ciechanowski zachodni',
    'Dobrzyński nad Drwęcą', 'Dobrzyński nad Wisłą', 'Dzierzgowski', 'Gąbiński',
    'Gostyniński', 'Makowski', 'Mławski wschodni', 'Mławski zachodni', 'Nasielski',
    'Płocki wschodni', 'Płocki zachodni', 'Płoński', 'Płoński południowy', 'Płoński północny',
    'Przasnyski', 'Pułtuski', 'Raciąski', 'Rypiński', 'Serocki', 'Sierpecki',
    'Strzegowski', 'Tłuchowski', 'Wyszogrodzki', 'Zakroczymski', 'Żuromiński',
  ],
  'Diecezja radomska': [
    'Czarnecki', 'Czarnoleski', 'Drzewicki', 'Głowaczowski', 'Iłżecki', 'Jedliński',
    'Konecki', 'Kozienicki', 'Lipski', 'Opoczyński', 'Pionkowski', 'Przedborski',
    'Przysuski', 'Przytycki', 'Radom-Centrum', 'Radom-Południe', 'Radom-Północ',
    'Radom-Wschód', 'Radom-Zachód', 'Radoszycki', 'Sienneński', 'Skarżyski',
    'Starachowice-Południe', 'Starachowice-Północ', 'Szydłowiecki', 'Tomaszowski',
    'Wierzbicki', 'Zwoleński', 'Żarnowski',
  ],
  'Diecezja rzeszowska': [
    'Biecz', 'Boguchwała', 'Brzostek', 'Czudec', 'Dębowiec', 'Frysztak',
    'Głogów Małopolski', 'Gorlice', 'Jasło Wschód', 'Jasło Zachód',
    'Kolbuszowa Wschód', 'Kolbuszowa Zachód', 'Nowy Żmigród', 'Ropczyce',
    'Rzeszów Fara', 'Rzeszów Katedra', 'Rzeszów Południe', 'Rzeszów Północ',
    'Rzeszów Wschód', 'Rzeszów Zachód', 'Sędziszów Małopolski',
    'Sokołów Małopolski', 'Strzyżów', 'Tyczyn', 'Wielopole Skrzyńskie',
  ],
  'Diecezja sandomierska': [
    'Baranów Sandomierski', 'Gorzyce', 'Janów Lubelski', 'Klimontów', 'Koprzywnica',
    'Kunów', 'Modliborzyce', 'Nisko', 'Nowa Dęba', 'Opatów', 'Ostrowiec Świętokrzyski',
    'Ożarów', 'Połaniec', 'Pysznica', 'Raniżów', 'Rudnik nad Sanem', 'Sandomierz',
    'Stalowa Wola', 'Staszów', 'Szewna', 'Świętokrzyski', 'Tarnobrzeg', 'Ulanów',
    'Zaklików', 'Zawichost',
  ],
  'Diecezja siedlecka': [
    'Adamów', 'Biała Podlaska – Południe', 'Biała Podlaska – Północ', 'Domanice',
    'Garwolin', 'Grębków', 'Hańsk', 'Janów Podlaski', 'Komarówka Podlaska',
    'Łaskarzew', 'Łosice', 'Łuków I', 'Łuków II', 'Międzyrzec Podlaski', 'Osieck',
    'Parczew', 'Radzyń Podlaski', 'Ryki', 'Siedlce', 'Suchożebry', 'Terespol',
    'Wisznice', 'Włodawa', 'Zbuczyn', 'Żelechów',
  ],
  'Diecezja sosnowiecka': [
    'Będzin – Trójcy Świętej', 'Będzin – św. Jana Pawła II', 'Czeladź',
    'Dąbrowa Górnicza – NMP Anielskiej', 'Dąbrowa Górnicza – św. Antoniego',
    'Dąbrowa Górnicza – NSJ', 'Jaroszowiec', 'Jaworzno – NMP Nieustającej Pomocy',
    'Jaworzno – Świętych Wojciecha i Katarzyny', 'Łazy', 'Olkusz', 'Pilica', 'Sączów',
    'Siewierz', 'Sławków', 'Sosnowiec – św. Barbary', 'Sosnowiec – Jezusa Chrystusa Króla',
    'Sosnowiec – św. Jadwigi Śląskiej', 'Sosnowiec – św. Tomasza Apostoła',
    'Sosnowiec – Wniebowzięcia NMP', 'Sułoszowa', 'Wolbrom – św. Katarzyny',
    'Wolbrom – Podwyższenia Krzyża Świętego',
  ],
  'Diecezja świdnicka': [
    'Bielawa', 'Bolków', 'Bystrzyca Kłodzka', 'Dzierżoniów', 'Głuszyca',
    'Kamieniec Ząbkowicki', 'Kłodzko', 'Kudowa-Zdrój', 'Lądek-Zdrój', 'Międzylesie',
    'Nowa Ruda', 'Nowa Ruda-Słupiec', 'Piława Górna', 'Polanica-Zdrój', 'Strzegom',
    'Świdnica-Wschód', 'Świdnica-Zachód', 'Świebodzice', 'Wałbrzych-Południe',
    'Wałbrzych-Północ', 'Wałbrzych-Zachód', 'Ząbkowice Śląskie-Południe',
    'Ząbkowice Śląskie-Północ', 'Żarów',
  ],
  'Diecezja tarnowska': [
    'Bobowa', 'Bochnia Wschód', 'Bochnia Zachód', 'Brzesko', 'Ciężkowice', 'Czchów',
    'Dąbrowa Tarnowska', 'Dębica Wschód', 'Dębica Zachód', 'Grybów',
    'Krościenko nad Dunajcem', 'Krynica-Zdrój', 'Limanowa', 'Lipnica Murowana',
    'Łącko', 'Łużna', 'Mielec Południe', 'Mielec Północ', 'Nowy Sącz Centrum',
    'Nowy Sącz Wschód', 'Nowy Sącz Zachód', 'Ołpiny', 'Pilzno', 'Piwniczna',
    'Porąbka Uszewska', 'Pustków-Osiedle', 'Radłów', 'Radomyśl Wielki', 'Ropa',
    'Stary Sącz', 'Szczepanów', 'Szczucin', 'Tarnów Południe', 'Tarnów Północ',
    'Tarnów Wschód', 'Tarnów Zachód', 'Tuchów', 'Tymbark', 'Ujanowice', 'Uście Solne',
    'Wojnicz', 'Zakliczyn', 'Żabno',
  ],
  'Diecezja toruńska': [
    'Bierzgłowo', 'Brodnica', 'Chełmno', 'Chełmża', 'Działdowo', 'Golub', 'Górzno',
    'Grudziądz I', 'Grudziądz II', 'Jabłonowo Pomorskie', 'Kowalewo Pomorskie',
    'Kurzętnik', 'Lidzbark Welski', 'Lubawa', 'Łasin', 'Nowe Miasto Lubawskie',
    'Radzyń Chełmiński', 'Rybno Pomorskie', 'Toruń I', 'Toruń II', 'Toruń III',
    'Toruń IV', 'Unisław', 'Wąbrzeźno',
  ],
  'Diecezja warszawsko-praska': [
    'Aniński', 'Bródnowski', 'Grochowski', 'Jadowski', 'Kobyłkowski', 'Legionowski',
    'Mińsk Mazowiecki – Narodzenia NMP', 'Mińsk Mazowiecki – św. Antoniego',
    'Nowodworski', 'Otwocki', 'Otwock-Kresy', 'Praski', 'Radzymiński', 'Rembertowski',
    'Siennicki', 'Stanisławowski', 'Sulejówek', 'Tarchomiński', 'Tłuszcz',
    'Wołomiński', 'Zielonkowski',
  ],
  'Diecezja włocławska': [
    'Aleksandrowski', 'Bądkowski', 'Brzeski', 'Chodecki', 'Czernikowski', 'Dobrski',
    'Izbicki', 'Kłodawski', 'Kolski', 'Koniński I', 'Koniński II', 'Koniński III',
    'Koronowski', 'Kościelecki', 'Kowalski', 'Lipnowski', 'Lubicki', 'Lubraniecki',
    'Nieszawski', 'Piotrkowski', 'Radziejowski', 'Sieradzki I', 'Sieradzki II',
    'Sompoleński', 'Szadkowski', 'Szpetalski', 'Ślesiński', 'Tuliszkowski', 'Turecki',
    'Uniejowski', 'Warcki', 'Włocławski I', 'Włocławski II', 'Zduńskowolski',
  ],
  'Diecezja zamojsko-lubaczowska': [
    'Biłgoraj-Południe', 'Biłgoraj-Północ', 'Cieszanów', 'Grabowiec',
    'Hrubieszów-Południe', 'Hrubieszów-Północ', 'Józefów', 'Krasnobród', 'Lubaczów',
    'Łaszczów', 'Narol', 'Sitaniec', 'Szczebrzeszyn', 'Tarnogród', 'Tarnoszyn',
    'Tomaszów-Południe', 'Tomaszów-Północ', 'Tyszowce', 'Zamość',
  ],
  'Diecezja zielonogórsko-gorzowska': [
    'Babimost', 'Drezdenko', 'Głogów – NMP Królowej Polski', 'Głogów – św. Mikołaja',
    'Gorzów Wlkp. – Chrystusa Króla', 'Gorzów Wlkp. – Katedra',
    'Gorzów Wlkp. – Trójcy Świętej', 'Gubin', 'Kostrzyn nad Odrą', 'Kożuchów',
    'Krosno Odrzańskie', 'Lubsko', 'Łęknica', 'Nowa Sól', 'Pszczew', 'Rokitno',
    'Rzepin', 'Sława', 'Strzelce Krajeńskie', 'Sulechów', 'Sulęcin', 'Szprotawa',
    'Świebodzin – Miłosierdzia Bożego', 'Świebodzin – NMP Królowej Polski', 'Wschowa',
    'Zielona Góra – Ducha Świętego', 'Zielona Góra – Podwyższenia Krzyża Świętego',
    'Zielona Góra – św. Jadwigi', 'Żagań', 'Żary',
  ],
  'Ordynariat Polowy': [
    'Bydgoski', 'Gdański', 'Krakowski', 'Lubelski', 'Olsztyński', 'Poznański',
    'Siedlecki', 'Szczeciński', 'Warszawski I', 'Warszawski II', 'Warszawski III',
    'Wrocławski', 'Żandarmerii Wojskowej',
  ],
};
